### ISSUE TITLE
WebdriverIO@8 compatibility

### ISSUE THREAD

**Issue by lukpe** [fjaguado/angular-wdio-builder#1]
When trying to launch tests after WebdriverIO upgrade from v7 to v8, I get this error:

`[error] TypeError: Launcher is not a constructor
    at C:\XXXX\node_modules\@migalons\angular-wdio-builder\lib\test.js:32:18
    at Generator.next (<anonymous>)
    at fulfilled (C:\XXXX\node_modules\@migalons\angular-wdio-builder\lib\test.js:5:58)`

I'm on Angular: 14.2.12.

**Comment by lukpe** [comment]
Sorry, wrong repo.
